COOKIE_SESSION = "ums_session"
COOKIE_CSRF = "ums_csrf"

ROLE_USER = "USER"
ROLE_ADMIN = "ADMIN"
ROLE_SUPER_ADMIN = "SUPER_ADMIN"

USER_STATUS_PENDING = "PENDING_VERIFICATION"
USER_STATUS_ACTIVE = "ACTIVE"
USER_STATUS_DISABLED = "DISABLED"
USER_STATUS_DELETED = "DELETED"

